#!/usr/bin/env python3
"""Generate and verify the live corpus-statistics block in README.md.

Narrative documentation should explain stable design. The one intentionally
live statistics block is generated from the committed corpus so a curation
change cannot leave plausible-looking old numbers behind.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from itertools import zip_longest
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
README = REPO_ROOT / "README.md"
HABITATS = REPO_ROOT / "data" / "habitats"
START = "<!-- BEGIN GENERATED CORPUS STATS -->"
END = "<!-- END GENERATED CORPUS STATS -->"

CATEGORY_ORDER = [
    "HOST_ASSOCIATED",
    "ENGINEERED",
    "AQUATIC",
    "TERRESTRIAL",
    "OTHER",
    "FOOD",
    "AIR",
    "CLINICAL",
]
GROUNDING_ORDER = ["EXACT", "UNGROUNDED", "NARROW", "NOT_APPLICABLE", "CLOSE", "BROAD"]


def load_records(root: Path = HABITATS) -> list[dict]:
    records = []
    for path in sorted(root.rglob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8"))
        if isinstance(doc, dict) and "identifier" in doc:
            records.append(doc)
    return records


def statistics_block(records: list[dict]) -> str:
    total = len(records)
    categories = Counter(r["habitat_category"] for r in records)
    groundings = Counter(r["grounding_status"] for r in records)
    mappings = Counter(r["mapping_status"] for r in records)
    source_counts = [len({a["source"] for a in r.get("source_attestations", [])}) for r in records]
    multi_source = sum(count >= 2 for count in source_counts)
    four_source = sum(count >= 4 for count in source_counts)
    reviewed = mappings["REVIEWED"]
    seeded = mappings["SEEDED"]
    reviewed_pct = (100 * reviewed / total) if total else 0

    category_rows = [(name, categories[name]) for name in CATEGORY_ORDER if categories[name]]
    grounding_rows = [(name, groundings[name]) for name in GROUNDING_ORDER if groundings[name]]
    table_rows = []
    for category, grounding in zip_longest(category_rows, grounding_rows, fillvalue=("", "")):
        c_name, c_count = category
        g_name, g_count = grounding
        c_value = f"{c_count:,}" if isinstance(c_count, int) else ""
        g_value = f"{g_count:,}" if isinstance(g_count, int) else ""
        table_rows.append(f"| {c_name} | {c_value} | | {g_name} | {g_value} |")

    return "\n".join(
        [
            START,
            "<!-- Generated by scripts/check_docs.py; do not edit this block by hand. -->",
            f"**{total:,} habitat records** are currently committed.",
            "",
            "| Category | Records | | Grounding | Records |",
            "|---|---:|---|---|---:|",
            *table_rows,
            "",
            f"{multi_source:,} records are attested by at least two sources; "
            f"{four_source:,} are attested by four or more.",
            "",
            f"**{reviewed:,} records ({reviewed_pct:.1f}%) are `REVIEWED`;** "
            f"the remaining {seeded:,} are `SEEDED`.",
            END,
        ]
    )


def update_readme(text: str, block: str) -> str:
    if START not in text or END not in text:
        raise ValueError(f"README must contain exactly one {START!r}/{END!r} marker pair")
    if text.count(START) != 1 or text.count(END) != 1:
        raise ValueError("README corpus-statistics markers must each occur exactly once")
    before, rest = text.split(START, 1)
    _old, after = rest.split(END, 1)
    return before + block + after


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="fail when README statistics are stale")
    mode.add_argument("--write", action="store_true", help="refresh the generated README block")
    args = parser.parse_args(argv or sys.argv[1:])

    current = README.read_text(encoding="utf-8")
    expected = update_readme(current, statistics_block(load_records()))
    if args.check:
        if current != expected:
            print("README corpus statistics are stale; run `just docs-stats`", file=sys.stderr)
            return 1
        print("README corpus statistics are current")
        return 0
    README.write_text(expected, encoding="utf-8")
    print("updated README corpus statistics")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
