#!/usr/bin/env python3
"""Check that DOIs cited in the research reports actually resolve.

The reports are prose generated by a model, and a fabricated DOI is
indistinguishable from a real one to a reader. That is the same problem
`tests/test_decisions.py` solves for curation notes by checking every CURIE
against the vendored slice; this is the equivalent for the research corpus.

An adversarial sample of 50 in #121 found 2 that resolve nowhere — roughly 4%,
so about 50 bad citations across 1,262 distinct DOIs. The reports are inputs to
a curator rather than records, so a bad citation costs a dead link and not a
corrupt corpus, but a curator writing a definition should know which reference
they cannot follow.

**Normalise before accusing.** The first version of this check reported three
failures and two were its own extraction bug: a DOI truncated at an unbalanced
parenthesis, and one carrying a `/full` suffix from the URL it was scraped out
of. A checker that cries wolf on its own regex is worse than none.

Usage:
    python3 scripts/check_report_citations.py --sample 50
    python3 scripts/check_report_citations.py --all --out reports/citations.tsv
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
RESEARCH_DIR = REPO_ROOT / "research"

# Deliberately permissive, because the normaliser below cleans up rather than
# the pattern being clever. A tight pattern silently drops real DOIs.
DOI_PATTERN = re.compile(r"10\.\d{4,9}/[-._;()/:A-Za-z0-9]+")

CROSSREF = "https://api.crossref.org/works/"
# Crossref asks for a contact address and gives the polite pool in return, which
# is the difference between working and being 429'd off the service.
USER_AGENT = "HabitatMech-citation-check/1.0 (mailto:mjoachimiak@lbl.gov)"


def _repo_relative(path: Path) -> str:
    """Display path, tolerating a relative --out. `Path.relative_to` raises on
    one, which crashed this script after it had already done all the work."""
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def normalise(doi: str) -> str:
    """Strip what scraping a DOI out of prose puts on the end of it."""
    doi = doi.rstrip(".,;:)]}")
    # URL path segments that follow a DOI in a publisher link.
    doi = re.sub(r"/(full|abstract|pdf|meta|epdf|html)$", "", doi, flags=re.I)
    # Markdown or sentence punctuation can leave an unbalanced opening paren,
    # which truncates a real DOI into one that resolves nowhere.
    if doi.count("(") > doi.count(")"):
        doi = doi[: doi.rindex("(")]
    return doi.rstrip(".,;:")


def collect() -> dict[str, list[str]]:
    """Every distinct DOI, mapped to the reports citing it."""
    found: dict[str, list[str]] = {}
    for path in sorted(RESEARCH_DIR.rglob("*.md")):
        text = path.read_text(encoding="utf-8")
        for raw in DOI_PATTERN.findall(text):
            doi = normalise(raw)
            if len(doi) > 10:
                found.setdefault(doi, []).append(str(path.relative_to(REPO_ROOT)))
    return found


def check(doi: str, attempts: int = 4) -> str:
    """`found`, an HTTP status, or an exception name.

    Retries 429 with linear backoff. Crossref rate-limits parallel clients
    hard enough that a concurrent checker reports far more failures than exist
    — which would be the same crying-wolf problem in a different place.
    """
    for attempt in range(attempts):
        try:
            request = urllib.request.Request(
                CROSSREF + urllib.parse.quote(doi), headers={"User-Agent": USER_AGENT}
            )
            with urllib.request.urlopen(request, timeout=30) as response:
                json.load(response)
                return "found"
        except urllib.error.HTTPError as error:
            if error.code == 429:
                time.sleep(6 * (attempt + 1))
                continue
            return f"HTTP {error.code}"
        except Exception as error:  # network flake, DNS, timeout
            if attempt == attempts - 1:
                return type(error).__name__
            time.sleep(3)
    return "rate-limited"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sample", type=int, default=50,
                        help="how many distinct DOIs to check (0 with --all)")
    parser.add_argument("--all", action="store_true", help="check every distinct DOI")
    parser.add_argument("--seed", type=int, default=20260817,
                        help="fixed so the same sample is drawn again; a rate quoted "
                             "against an unrepeatable sample cannot be rechecked")
    parser.add_argument("--out", type=Path, help="write per-DOI results to a TSV")
    args = parser.parse_args(argv)

    citations = collect()
    if not citations:
        print("no DOIs found under research/")
        return 0

    # Hash-based, so the sample is a property of each DOI rather than of the
    # list — the corpus grows and the previous sample stays meaningful.
    ordered = sorted(
        citations, key=lambda d: hashlib.sha1(f"{args.seed}:{d}".encode()).hexdigest()
    )
    subject = ordered if args.all else ordered[: args.sample]

    results = [(doi, check(doi)) for doi in subject]
    bad = [(d, s) for d, s in results if s != "found"]
    unresolved = [(d, s) for d, s in bad if s.startswith("HTTP")]

    print(f"{len(citations)} distinct DOIs across {len(set(sum(citations.values(), [])))} reports")
    print(f"checked {len(results)}: {len(results) - len(bad)} found, {len(bad)} not")
    if unresolved:
        rate = 100 * len(unresolved) / len(results)
        print(f"\n{len(unresolved)} resolve nowhere ({rate:.1f}% of those checked):")
        for doi, status in unresolved:
            where = citations[doi][0]
            print(f"  {status:9s} {doi}\n            cited in {where}")
    inconclusive = [b for b in bad if not b[0].startswith("HTTP")]
    if inconclusive:
        print(f"\n{len(inconclusive)} inconclusive (network or rate limit), not counted as bad")

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        with args.out.open("w", newline="", encoding="utf-8") as fh:
            writer = csv.writer(fh, delimiter="\t", lineterminator="\n")
            writer.writerow(["doi", "status", "citing_reports"])
            for doi, status in results:
                writer.writerow([doi, status, len(citations[doi])])
        print(f"\nwrote {_repo_relative(args.out)}")
    # Non-zero only on DOIs that definitively do not exist.
    return 1 if unresolved else 0


if __name__ == "__main__":
    raise SystemExit(main())
